### ISSUE TITLE
please test with flang

### ISSUE THREAD

**Issue by jeffhammond** [modern-fortran/neural-fortran#185] opened 2024-07-26 07:25 UTC
Can you please test with Flang?  https://github.com/jeffhammond/HPCInfo/blob/master/buildscripts/llvm-git.sh will install it for you.

I tried but the CMake junk for HDF5 is not working and I do not have the patience to deal with CMake right now.

Thanks.

**Comment by milancurcic** [comment] 2024-07-26 23:03
Sounds good, will try next week. Have you tried with fpm?

**Comment by milancurcic** [comment] 2024-08-13 14:46
I'm currently blocked building HDF5 with flang-new because of https://github.com/HDFGroup/hdf5/issues/3731. HDF5 is currently a required dependency for neural-fortran, more out of laziness than by design.

I've been meaning to make HDF5 optional, which will simplify many things including this one.

**Comment by milancurcic** [comment] 2024-09-03 15:41
The fixes are now merged into `main` and I added flang-new (is that the correct name for this compiler?) to the list of tested compilers. I'll close this now. Please reopen if something more is needed.

**Closed by milancurcic** 2024-09-03 15:41 UTC
